services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  category-svc:
    container_name: category-svc
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    working_dir: /usr/src/bb-category-svc
    volumes:
      - ../services/bb-category-svc:/usr/src/bb-category-svc
    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/categories
    depends_on:
      - mongo

  bb-gui:
    container_name: bb-gui
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    ulimits:
      nofile:
        soft: 40960
        hard: 40960
    working_dir: /usr/src/bb-gui
    volumes:
      - ../gui:/usr/src/bb-gui
    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - 80:3000
    environment:
      CATEGORY_SVC_URI: http://catalog-svc:3000
    depends_on:
      - category-svc

volumes:
  mongo-data:
